{{- if .Values.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-pvc" (include "note-discovery.fullname" .)) .Values.pvc.name | quote }}
  labels:
    {{- include "note-discovery.labels" . | nindent 4 }}
    {{- with .Values.pvc.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    {{- toYaml .Values.pvc.resources | nindent 4 }}
  {{- with .Values.pvc.volumeName }}
  volumeName: {{ . | quote }}
  {{- end }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
{{- end }}
